# config.toml
id_start_value              = 10000
id_inc_value                = 1000
allow_dynamic_tables        = true
data_home_dir               = "~/Workspace/Data"

[system_table_names]
table_name_test             = "test"
table_name_login_sessions   = "login_sessions"
table_name_session_log      = "session_log"
table_name_users            = "users"
table_name_activity_log     = "activity_log"
table_name_id_mgr           = "id_mgr"
table_name_email_store      = "email_store"
table_name_prompt_store     = "prompt_store"
table_name_resources        = "resources"
table_name_table_manager    = "table_manager"

[system_ids]
activity_log_id             = "IDs for activity log"
prompt_store_id             = "IDs for prompt store"

[icon_service]
enable_icon_service         = "enabled"
icon_data_dir               = "icons"

[proc_log]
log_file_dir                = "~/ProcLog"
file_max_size_in_mb         = 100
num_log_files               = 20